name: test

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php70
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install composer packages
        run: |
          composer install \
            --dev \
            --optimize-autoloader \
            --no-interaction
      - run: tar -vcf app.tar --exclude .git ./
      - uses: actions/upload-artifact@master
        with:
          name: app
          path: ./app.tar

  code-style:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php70
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - run: vendor/bin/php-cs-fixer fix -vvv

  phpstan:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php70
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - name: phpstan analyse
        run: |
          vendor/bin/phpstan analyse \
            -c phpstan.neon \
            -- src test

  unit-tests-php70:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php70
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - run: vendor/bin/phpunit

  unit-tests-php71:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php71
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - run: vendor/bin/phpunit

  unit-tests-php72:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php72
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - run: vendor/bin/phpunit

  unit-tests-php73:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php73
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - run: vendor/bin/phpunit

  unit-tests-php74:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: math3usmartins/php-minibus-builder:php74
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app
          path: ./
      - run: tar -xf ./app.tar
      - run: vendor/bin/phpunit
